
WorkOrder.create(container_count: 100, boat_id: 4, origin_port_manager_id: 1, destination_port_manager_id: 8, name: "Merck", description: "Shippment of pharmaceuticals to be distributed throughout Eastern Africa.  Terms: FOB Destination", complete: false, salesman_id: 1)

BoatWorkOrder.create(boat_id: 4, work_order_id: 1)

SalesmanBoat.create(salesman_id: 1, boat_id: 4)

Salesman.create(email: "kevin@kkr.com", password: "123", territory: "Europe")
Salesman.create(email: "kns@kkr.com", password: "123", territory: "Asia")
Salesman.create(email: "richard@kkr.com", password: "123", territory: "Americas")
Salesman.create(email: "africa@kkr.com", password: "123", territory: "Africa")

Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)
Container.create(work_order_id: 1, weight: 2, cargo_type: 1)

PortManager.create(email: "Shanghai@KKR.com", password: "123", location: "Shanghai")
PortManager.create(email: "Singapore@KKR.com", password: "123", location: "Singapore")
PortManager.create(email: "LA@KKR.com", password: "123", location: "Los Angeles")
PortManager.create(email: "Savannah@KKR.com", password: "123", location: "Savannah")
PortManager.create(email: "Rotterdam@KKR.com", password: "123", location: "Rotterdam")
PortManager.create(email: "Hamburg@KKR.com", password: "123", location: "Hamburg")
PortManager.create(email: "Panama@KKR.com", password: "123", location: "Panama")
PortManager.create(email: "Santos@KKR.com", password: "123", location: "Santos")
PortManager.create(email: "Durban@KKR.com", password: "123", location: "Durban")
PortManager.create(email: "Kenya@KKR.com", password: "123", location: "Kenya")

Boat.create(name: "Edmund Fitzgerald", container_limit: 300, destination_port_manager_id: 7, at_sea: false)
Boat.create(name: "Orca", container_limit: 300, destination_port_manager_id: 6, at_sea: false)
Boat.create(name: "Captayannis", container_limit: 100, destination_port_manager_id: 9, at_sea: false)
Boat.create(name: "USS Arizona", container_limit: 100, destination_port_manager_id: 10, at_sea: false)
Boat.create(name: "Foxhound", container_limit: 300, destination_port_manager_id: 8, at_sea: false)
Boat.create(name: "Sivo ", container_limit: 50, destination_port_manager_id: 10, at_sea: false)
Boat.create(name: "Lusitania", container_limit: 50, destination_port_manager_id: 4, at_sea: false)
Boat.create(name: "Sansinena", container_limit: 20, destination_port_manager_id: 3, at_sea: false)
Boat.create(name: "Exxon Valdez", container_limit: 20, destination_port_manager_id: 2, at_sea: false)
Boat.create(name: "Suilven", container_limit: 300, destination_port_manager_id: 5, at_sea: true)
Boat.create(name: "The Bismarck", container_limit: 10, destination_port_manager_id: 10, at_sea: true)
Boat.create(name: "Costa Concordia", container_limit: 50, destination_port_manager_id: 1, at_sea: true)
Boat.create(name: "Sewol", container_limit: 50, destination_port_manager_id: 1, at_sea: false)
Boat.create(name: "Maple Lea", container_limit: 300, destination_port_manager_id: 4, at_sea: false)
Boat.create(name: "Titanic", container_limit: 200, destination_port_manager_id: 3, at_sea: false)
Boat.create(name: "Dona Paz", container_limit: 200, destination_port_manager_id: 2, at_sea: false)
Boat.create(name: "Le Joola", container_limit: 100, destination_port_manager_id: 1, at_sea: false)
Boat.create(name: "Vasa", container_limit: 100, destination_port_manager_id: 7, at_sea: false)
Boat.create(name: "World Discoverer", container_limit: 100, destination_port_manager_id: 2, at_sea: false)
Boat.create(name: "Schooner Sweepstakes", container_limit: 10, destination_port_manager_id: 10, at_sea: false)
Boat.create(name: "Sea Lion", container_limit: 50, destination_port_manager_id: 6, at_sea: false)
Boat.create(name: "El Faro", container_limit: 300, destination_port_manager_id: 9, at_sea: false)
Boat.create(name: "Flinterstar", container_limit: 300, destination_port_manager_id: 10, at_sea: false)



